---
- hosts: all
  user: ansible
  become: True
  tasks:
    - name: Install NTP
      yum:
        pkg: ntp
        state: installed
    
    - name: Start NTP
      command: service ntpd start

    - name: Stop firewalld/iptables
      command: service firewalld stop

#    - name: Stop iptables6
#     command: service ip6tables stop

#    - name: If needed temporaly disable SELinux
#     shell: echo 0 > enforce
#    args:
#        chdir: /selinux
#        removes: enforce

#    - name: Disable SElinux permanetly
#      lineinfile: dest=/etc/sysconfig/selinux state=present create=no regexp='SELINUX=.*' line='SELINUX=disabled'
    
    - name: Disable selinux
      selinux:
        state: disabled

    - name: Create hostname entry to "master.subex.com"
      lineinfile: dest=/etc/hostname state=present create=yes regexp='.*' line='master.subex.com'

    - name: Set networking yes
      lineinfile: dest=/etc/sysconfig/network create=yes state=present regexp='NETWORKING=.*' line='NETWORKING=yes'

    - name: Set hostname to "master.subex.com"
      lineinfile: dest=/etc/sysconfig/network create=yes state=present regexp='HOSTNAME=.*' line='HOSTNAME=master.subex.com'

    - name: Create Ambari Repo {{ hdp_ambari_repo }}
      command: wget http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.2.0/ambari.repo -O /etc/yum.repos.d/ambari.repo

    - name: Clean YUM
      command: yum clean all

    - name: Install Ambari Agent
      yum:
        pkg: ambari-agent
        state: installed

    - name: Configure Ambari agent to register at Ambari server
      lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini create=no state=present regexp='hostname=.*' line='hostname=master.subex.com'

- hosts: all
  user: ansible
  become: True
  tasks: 
    - name: Install Ambari server
      yum:
        pkg: ambari-server
        state: installed

    - name: Configure Ambari server
      command: ambari-server setup -s

    - name: Sleep
      command: sleep 10

    - name: Start Ambari server
      command: ambari-server start
